### ISSUE TITLE
Start Node: Add all Attributes at 1 as default

### ISSUE THREAD

**Issue by Sandworm4** [FreddieRa/SkillTrees#17]
All Attributes are at 1 in Era d10, so it's important that's included in the count, or things go horribly wrong with the totals when checking the tree!

I think it's best to reduce the "blind typing" that has to be done with the Start Node and just add everything, then it can be edited through the interface afterwards - it's sort of a pain to remember numbers and type them and then be unable to check.

I think we could add all Attributes at 1, enter the Skills in the prompt and any Attributes we enter override the value of 1.

Is that doable?

**Comment by FreddieRa** [comment]
So the starting skills and attributes that you get in a tree aren't added to the 1 that you start with? They overrride it?

**Comment by FreddieRa** [comment]
If that is the case, this has been implemented

**Comment by Sandworm4** [comment]
Correct, yes.
