### ISSUE TITLE
Please change skillTable to the below

### ISSUE THREAD

**Issue by Sandworm4** [FreddieRa/SkillTrees#2]
skillTable = {
	"MAN": "Manifest",
	"INV": "Investigation",
	"ENE": "Enemy Skill",
	"STE": "Stealth",
	"GUN": "Gunnery",
	"BRA": "Brawl",
	"MEL": "Melee",
	"SUR": "Survival",
	"LAR": "Larceny",
	"EXP": "Explosives",
	"BOO": "Boost",
	"HEA": "Heal",
	"TIM": "Time",
	"FIR": "Fire",
	"ICE": "Ice",
	"LIG": "Lightning",
	"EAR": "Earth",
	"VOI": "Void"
}

**Comment by FreddieRa** [comment]
Fixed
