### ISSUE TITLE
Add the Calculate All function to the Tree Builder

### ISSUE THREAD

**Issue by Sandworm4** [FreddieRa/SkillTrees#20]
I have to very frequently save what I'm doing and transfer over to the checker in order to find out whether I'm doing things right.

This is the most common reason, followed by "How much of each Stat do I have?". I think it would help a lot to have a function that did this count for what I've currently got and then can vanish when I make any change.

**Comment by FreddieRa** [comment]
This has been added. Currently "9" on the keyboard, is there somewhere you would prefer it?
