### ISSUE TITLE
Add Initial amounts for each Tree

### ISSUE THREAD

**Issue by Sandworm4** [FreddieRa/SkillTrees#3]
Each tree comes with an initial Skill and Attribute set.
This affects the total number that can be reached through the Tree, such as this on White Magic:
2 Pow, 3 Int, 2 Stam, 3 Will, 2 Luck
1 Boost, 1 Heal, 1 Investigation, 1 Stealth, 1 Time, 1 Manifest, 1 Void

These are starting amounts you get with the Tree.

**Comment by FreddieRa** [comment]
This is the first non-trivial fix, so I will start to work on this tomorrow.

**Comment by FreddieRa** [comment]
This is now implemented, documentation will follow.
